---
title: "Forecasting: principles and practice"
author: "Rob J Hyndman"
date: "Wrap up"
fontsize: 14pt
output:
  beamer_presentation:
    fig_width: 7
    fig_height: 4.3
    highlight: tango
    theme: metropolis
    includes:
      in_header: header.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  cache=TRUE,
  warning=FALSE,
  message=FALSE)
library(fpp2)
options(digits=4, width=55)
```

## Workshop resources

\large

 * Slides
 * Exercises
 * Textbook
 * Useful links

\vspace*{1cm}\begin{alertblock}{}{\centerline{\large\textbf{\url{robjhyndman.com/acemsforecasting2018}}}}
\end{alertblock}

## Useful resources for forecasters
\fontsize{13}{14}\sf

\hspace*{-0.5cm}\begin{tabular}{@{}lp{7cm}}
\alert{Datacamp course:} & \texttt{bit.ly/dcforecasting} \\[0.3cm]
\alert{Organization:} &\RaggedRight International Institute of Forecasters. \texttt{forecasters.org} \\[0.3cm]
\alert{Annual Conference:} &\RaggedRight International Symposium on Forecasting, Thessaloniki, June 2019. \texttt{isf.forecasters.org} \\[0.3cm]
\alert{Blog:} & \texttt{robjhyndman.com/hyndsight} \\[0.3cm]
\alert{Finding information:} & \texttt{fpc.forecasters.org} \\[0.3cm]
\alert{Questions on R:} & \texttt{stackoverflow.com} \\[0.3cm]
\alert{Questions on statistics:} & \texttt{crossvalidated.com}
\end{tabular}

\pause\vspace*{1cm}

### Happy forecasting
Good forecasters are not smarter than everyone else, they merely have their ignorance better organised.

